apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: pavlenko-korolyov
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: svvvyt/ducker:1.0.lab
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: MARIADB_HOST
          value: "mariadb-service"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: pavlenko-korolyov
spec:
  serviceName: "mariadb-service"
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "example"
        volumeMounts:
        - name: mariadb-storage
          mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: mariadb-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-path
        resources:
          requests:
            storage: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: pavlenko-korolyov
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
  clusterIP: None
