version: 'lab'

services:
  app:
    build: ./app
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
    ports:
      - "8080:80"

  mariadb:
    image: mariadb:11.5
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"